name: Feature branch updated

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  run-tests:
    if: ${{ !contains(github.event.head_commit.message, '--skip-ci') }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'


      - name: Install dependencies
        run: yarn install

      # - name: Run tests
      #   run: yarn test --ci


      - name: Build
        run: yarn build